### ISSUE TITLE
Parenthesis problems with print

### ISSUE THREAD

**Issue by hugocth** [DependableSystemsLab/GPU-Injector#5]
Hello, is it normal that there are missing parenthesis in all your code after the prints ? For example : faultInjection.py, line 111
```
def runChecker(cmd,check_str):
    p = Popen(cmd,shell=True,stdout=PIPE,stderr = PIPE)
    stdout, stderr = p.communicate()
    print stdout # here
    print stderr # here
    if check_str in stdout:
        return 0;
    else:
        return -1;
```
Sadly because of this I can't run the benchmark ...

Best regards,
Hugo

**Comment by karthikp-ubc** [comment]
You may be using Python3. We only support Python 2, for which you don't need parantheses around the print statements. Thanks.
